### ISSUE TITLE
Spec precludes atomic RMW on larger ranges to implement smaller-range atomics

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#10]
On eg MIPS32 and PPC there are no byte and halfword atomic operations (LL/SC on these systems); this is true also for early ARMv6 systems.  On such systems it is probably best to implement byte and halfword atomics using word-width LL/SC and bitwise operations.  But the current spec text may prohibit that.  The reason is that the spec for SetValueInBuffer explicitly forbids RMW, while the specs for the atomics delegate to SetValueInBuffer.

**Comment by lars-t-hansen** [comment]
Indeed I wonder whether RMW atomics _can_ be a valid implementation technique for ES programs.  In C++ an atomic cell can be any size the implementation chooses, for its own convenience.  But in ES a cell can be as small as the program chooses, including a single byte.  Suppose we have three threads accessing two adjacent byte cells: two threads use atomic operations on their shared cell, the third uses non-atomic operations on its private cell.  No thread has a race at any time.  But if the atomic operation is implemented by RMW on a word, then the program as a whole does contain a race, because atomic and non-atomic accesses are used on the same memory - on overlapping non-identical ranges, to boot.

On ARM this probably results in implementation defined behavior (ARMv7 manual A3.4.1) because it's not defined whether the store from the unsynchronized-access thread is going to interact with the reservation monitor for the exclusive access used in the two other threads.

(Visibility: @jfbastien, @lukewagner)

**Comment by lukewagner** [comment]
That's a good point!  I guess one option is to change the definition of race to instead refer to the containing N-byte aligned range, not just the K bytes operated on by the atomic op (either fixing N to 4 or exposing N as some immutable `Atomics.atomicWidth` property).  Or, we could simply drop sub-int32 atomic ops altogether.

So, for C++, are there no "raw" atomic non-member functions that operate on plain pointers?

**Comment by jfbastien** [comment]
@lukewagner there are free-standing atomic functions, for C compatibility (put in without consulting the C committee...).

In general the memory model says that accessing the same memory location atomically and non-atomically is UB. The `std::atomic` type and C's `_Atomic` can add extra alignment or padding restrictions, which at our IR level we're unaware of. This means that the front-end (not middle- or back-end!) has to know what the destination platforms looks like, and whether it can support collocating say `std::atomic<uint8_t>` and `uint8_t` in the same word. If not then it's the front-end's responsibility to pad them so there isn't any UB.

Your issues basically exposes this expectation. We're not operating at the same level (we only tag accesses as atomic or not, we don't know about objects and memory locations), but we have a similar restriction that isn't spelled out: collocating atomic and non-atomic values "too close" leads to bounded non-determinism (instead of UB) where updates to the atomic location may lose updates to the non-atomic one that was too close.

I hope this makes sense!

**Comment by lars-t-hansen** [comment]
@lukewagner, exposing an immutable Atomics.atomicWidth property without a universally known value is probably not very useful since emscripten would have to open-code this anyhow and that value would have to be valid on all platforms.  I suspect this is the same point @jfbastien is making regarding the front-end.

We could restrict atomics to int32, but I don't think we should - in that case it would be strictly more useful to provide atomics at 1 and 2 byte granularities even if those were not lock-free.  Also, non-lock-free atomics at 1 and 2 bytes are currently a problem only on platforms seen as "minor" (early ARMv6, PPC, MIPS) - and strictly speaking only if the processor definition makes it implementation dependent what happens when a regular store interacts with an LL/SC pair (though I expect that to be an issue on all platforms).

However, this brings us back to issue 300 from the WebAssembly/design repo, namely, is there some granularity that we can assume universally will be lock-free, notably, 4 bytes?  If so, then perhaps emscripten could just pad std::atomic to four bytes in all cases.

**Comment by lukewagner** [comment]
@lars-t-hansen Yes, I was assuming `atomicWidth` would have a specified upper bound (probably 4) which could then be assumed AOT by compilers.  Specifying exactly 4 (and so no need for a property) is even simpler and sounds like a fine option to me.  The fact that this number gets statically baked into the code (not just as a literal number, but implicitly as struct/array sizes/offsets that permeate the whole program) means that there isn't much opportunity for code to dynamically test and leverage a smaller `atomicWidth`.

My reason for asking about C++ non-member-function atomic APIs was to ask how they specified this requirement, since they'd have the same problem as we have here.

**Comment by sunfishcode** [comment]
@lars-t-hansen 

>  In C++ an atomic cell can be any size the implementation chooses, for its own convenience.

Does this refer to the standard permitting `atomic<T>` to have a different size and alignment than `T`? If so, one data point here is that clang at least doesn't currently contain code to take advantage of this. It uses the size and alignment of `T` (except in odd non-power-of-2 cases) for all platforms.

**Comment by lars-t-hansen** [comment]
Conclusion (for now): The spec will continue to require non-RMW behavior, and if that requires implementing 1-byte and 2-byte atomics with a lock then so be it.

Note that only observed behavior is legislated so if, as @jfbastien says, ARM implementations uniformly clear the global monitor on a normal store then on older ARM without byte and halfword exclusive ops the byte and halfword exclusive ops should still be implementable using the word ops.

**Comment by lars-t-hansen** [comment]
I read some more hardware manuals, and I think that on all mainstream platforms it should in principle be fine to implement eg byte atomics using word atomics.
- On ARM, a normal store clears any reservation it interacts with, and the reservation size is at least 8 bytes (ARMv7 manual).  Thus a RMW byte atomic that interacts with an adjacent non-atomic byte will be fine.  (Only an issue on very early ARMv6 and earlier architectures.)
- On MIPS, where we have word (and on MIPS64, doubleword) exclusives, the manual states that a normal store to a reserved address clears the reservation. 
- On Power8, the reservation size is 16 bytes and the manual states that a normal store to a reserved address clears the reservation.

In those cases a store to a byte next to an atomic byte can happen before the load-exclusive or after the store-exclusive, and if it happens between the load-exclusive and the store-exclusive then it will force a retry.

**Comment by lars-t-hansen** [comment]
To summarize:
- The spec retains its current prose, RMW is not allowed.
- On many platforms we care about, atomic RMW is _possible_ in the implementation because a regular store clears the exclusive monitor and the monitor covers at least a word, often more.
- If there are platforms where an atomic access adjacent to a non-atomic access leads to weird interactions then the implementation must avoid those interactions, usually this means making the atomic access non-lock-free.  RMW is an example of "weird interaction" -- but there might be other kinds, suppose for the sake of argument that some mythical hardware needs to use the word adjacent to the atomic word as a coordination location for the access.
