### ISSUE TITLE
What does == mean in the new %TypedArray%.prototype.set

### ISSUE THREAD

**Issue by domenic** [tc39/ecmascript_sharedmem#109]
> If ..., let same = SharedDataBlockID(x.[[SharedArrayBufferData]]) == SharedDataBlockID(y.[[SharedArrayBufferData]]); otherwise let same = SameValue(srcBuffer, targetBuffer). 

I have no idea what this == is meant to mean.

Maybe this is supposed to be:
1. If ...
   1. Let _same_ be SharedDataBlockId(x.[[SharedArrayBufferData]])
   2. Assert: _same_ is equal to SharedDataBlockId(y.[[SharedArrayBufferData]])
2. Otherwise, let _same_ be SameValue(srcBuffer, targetBuffer).

**Comment by lars-t-hansen** [comment]
It is supposed to denote value equality, but I suppose since SharedDataBlockID returns a value that is only lightly specified this can be confusing.  (In addition, as I note in #108, there are other bugs here.)

In the course of fixing other bugs I have already changed the wording here to use "equals" and fixed the bugs mentioned in #108; what I will do in addition is make sure that the definition of the shared data block ID is sufficiently clear about the meaning of equality.

**Comment by lars-t-hansen** [comment]
Also, I'll come back to this issue when I tackle #114.
