### ISSUE TITLE
Should the atomics really be defined in terms of ECMAScript functions?

### ISSUE THREAD

**Issue by domenic** [tc39/ecmascript_sharedmem#120]
> Let xor denote a semantic function of two Integer arguments that computes the same result as the ECMASCript function `(a,b) => a^b`.

In particular this implies a and b are doubles, not integers.

At the very least you probably want to use more vague phrasing like https://tc39.github.io/ecma262/#sec-binary-bitwise-operators-runtime-semantics-evaluation does. But you may need to specify how this applies to different value ranges...

**Comment by jfbastien** [comment]
However the outcome ends up being, I'd like to have an English translation (in this bug, not the spec) of what the choice means. Do I get the same bitwise op (and / or / xor) semantics as in C, and which behavior do I get for signed and unsigned integer arithmetic (add / sub)?

**Comment by lars-t-hansen** [comment]
@jfbastien, I believe there is no confusion about the meaning.  It means what it should mean - due to how truncation works when the result is stored - this is just about how to express it in spec language.

Also see #118 (cc @littledan).

I'm regretting creating this abstract operation, since the amount of semantic discussion it has resulted in has caused more work for me than maintaining all the copies of the common code.

I am, for the time being, going to change from "Integer" to "Number" in the spec as concluded in #118.

Leaving this bug open for now.

**Comment by littledan** [comment]
I think this should be specified in terms of Numbers, since the operands come from (a version of) GetValueFromBuffer or scalar JS values, and the result is put in place with (a version of) SetValueInBuffer. I don't see what creating an abstract operation has to do with it--you have to specify semantics either way. The only objection I have to the arrow function phrasing is that it may be viewed as a "layering violation" to use an ES function in the definition of something. In the SIMD.js spec, I referred directly to the operator definition, e.g., https://tc39.github.io/ecmascript_simd/#simd-add . Any thoughts on using that sort of pattern here?

**Comment by lars-t-hansen** [comment]
@littledan, No objection to following SIMD.js here.

**Comment by lars-t-hansen** [comment]
On reflection, I'm not sure the SIMD.js spec makes any more sense here.  For "add" it references what is effectively an algorithm for interpreting an abstract syntax tree, which is not appropriate there, where eg SIMDConstructor.add is a function where the operands are already evaluated and known to be numbers.  That means the first nine steps of the add algorithm (charitably interpreted since its input is an AST fragment) are no-ops, leaving only "Return the result of applying the addition operation to lnum and rnum."

For its bitwise operations, the SIMD.js spec does not reference the ES spec at all, it defines its own abstract operator BitwiseOp(op) where op is a bitwise operator such as & that is not further defined (AFAICT), and applies that to the Int32 conversions of the input arguments.  If anything this is the better style.

How about this instead for the SAB spec:

(For add and subtract) "Let `add` (`sub`) denote a semantic function of two Number arguments that applies the addition (subtraction) operation to the arguments and returns the result of that operation."

(For the bitwise ops) "Let `and` (`or`, `xor`) denote a semantic function of two Number arguments that converts both arguments to Int32 by the ToInt32 operation, then applies the bitwise-and (-or, -xor) operation to the converted values, and returns the result of that operation."  Obviously since the inputs are numbers the order of conversion does not matter.  I could flesh that out as in the SIMD.js spec if desired, though it does not add any clarity.

**Comment by littledan** [comment]
Good points. Your plan seems reasonable. Maybe include a NOTE which explains that this implements two's complement overflow semantics due to the following SetValueInBuffer (for the case of `add` and `sub`).
