### ISSUE TITLE
{Read,Write}SharedMemory alignment

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#127]
IIUC `{Read,Write}SharedMemory` can only be called from `{Get,Set}ValueFromBuffer` which ensures that `elementSize` is one of {8,16,32}.

I don't understand what guarantees that `byteIndex` ensures proper alignment. The only restriction I see is:

> Assert: `byteIndex` is an integer value ≥ 0.

That's insufficient to ensure natural alignment (and lock-freedom).

There's the following mention:

> the byte array of a Shared Data Block can be aliased by TypedArrays of different types and accessed without natural alignment via DataViews

That seems to be a further complication: are atomic accesses accesses automatically  marked as "non-viable" (as defined by the memory model) if they're performed through a non-naturally-aligned DataView?

**Comment by jfbastien** [comment]
Ha, this seems covered by `ValidateAtomicAccess` which is called before `{Get,Set}ValueFromBuffer`?

This means that any misaligned access causes an exception, not simple tearing. This (naively) seems expensive? Especially if it implies ordering guarantees on the fault's occurrence.

**Comment by jfbastien** [comment]
...but then `ValidateAtomicAccess` doesn't check `typedArray.[[ByteOffset]]` which breaks both alignment _and_ bounds check.

**Comment by lars-t-hansen** [comment]
ReadSharedMemory and WriteSharedMemory are used for all accesses to shared memory, even for Float64Array (and Float32Array and Uint8ClampedArray, for completeness), so the elementSize is 8, 16, 32, or 64.

For example, follow the logic from ta[n] (for any TypedArray ta) to IntegerIndexedElementGet to GetValueFromBuffer to ReadSharedMemory, or from DataView's GetViewValue to GetValueFromBuffer to ReadSharedMemory.

The question of alignment came up recently in #117.  I added a section to DISCUSSION.md called "Implementation constraints from data race semantics" intending to clarify what I thought was a consequence of the spec, namely, that the only sane implementation strategy is to make sure that the memory for a SharedArrayBuffer is at least 4-byte aligned.  (4-byte atomic accesses must be lock-free so on eg ARM there must be alignment.)  From that we get proper alignment for atomic accesses, because a TypedArray can only be mapped onto a (Shared)ArrayBuffer with appropriate alignment, you can't align it not on a 4-byte offset from the start of the SAB.

Atomics are not available via DataView, but in any case if an access through a DataView conflicts with an atomic access through a TypedArray then this is a race and the atomic is not viable. 

Edit: fixed syntax.

**Comment by lars-t-hansen** [comment]
In general, range checking for eg ta[n] is handled by IntegerIndexedElementGet, and for atomic accesses it is handled by ValidateAtomicAccess, which only need check the range of the TypedArray.  The TypedArray is always in-bounds within the underlying buffer (checked at construction time and then invariant) and always properly aligned within it (checked at construction time as explained above); alignment of the buffer is then enforced by the need to implement lock-free atomics.

(Closing this; do reopen if you think my reasoning is flawed.)
