### ISSUE TITLE
Memory resizing race

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#129]
WebAssembly supports growing the memory's size, and obtaining its current size:
https://github.com/WebAssembly/design/blob/56e617e8144a8b750a1198871eb6d43fad182c21/AstSemantics.md#resizing
- Many of the spec's algorithms check that accesses are in-range. What happens if one of the algorithms is executing while a resize operation occurs?
- What happens if memory is resized during an access?

I assume _all_ threads need to be suspended for a resize operation.

**Comment by lars-t-hansen** [comment]
Resizing memory is definitely outside of scope for current work, though these are interesting points (also see #59 for other wasm discussion).

**Comment by lars-t-hansen** [comment]
The wasm threads spec is now addressing this.  I don't think thread suspension during resizing is required there (because a maximum size is always needed and memory will generally be preallocated, or pre-reserved); rather, it seems that a new SAB object is allocated with a larger length field, so operations on the memory will see the old or new SAB.  In either case, we'll move the discussion over there.
