### ISSUE TITLE
Should TypedArray methods that create ArrayBuffer be allowed to create SharedArrayBuffer?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#29]
The specification extends the TypedArray specification to allow TypedArrays to view SharedArrayBuffers.

There is a question whether existing TypedArray methods that create a new TypedArray on top of a new ArrayBuffer (TypedArray.prototype.filter, TypedArray.prototype.map, TypedArray.prototype.slice, TypedArray.prototype.subarray) should continue to create an ArrayBuffer even if the input buffer is a SharedArrayBuffer, or whether they should instead create a SharedArrayBuffer in that case.

Currently the spec specifies that ArrayBuffers are created in all cases.  I think this is the right decision, but I'm wondering if there are opinions to the contrary.

**Comment by littledan** [comment]
No really strong opinion, but I can't think of a use case for where you'd want a SharedArrayBuffer as output here. Since we went with the unified hierarchy, let's just do what naturally falls out of the rest of the spec text, which is to create a non-shared ArrayBuffer backing the output. This is a sort of "natural consequence" of _TypedArray_(n) being backed by an ArrayBuffer.

**Comment by lars-t-hansen** [comment]
OK.  Since there's been no disagreement in seven months, let's take this as resolved.
