### ISSUE TITLE
Should ArrayBuffer.isView and SharedArrayBuffer.isView be different?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#32]
Currently ArrayBuffer.isView is identical to SharedArrayBuffer.isView.  The immediate reason is that TypedArrays use the [[ViewedArrayBuffer]] internal slot to hold both unshared and shared views.

There is an opportunity to do something more interesting, namely, to make SharedArrayBuffer.isView() return ~true~ only if its argument is viewing a SharedArrayBuffer, and to make ArrayBuffer.isView() return ~false~ if its argument is viewing a SharedArrayBuffer.

Opinions, please.

**Comment by lars-t-hansen** [comment]
@littledan @allenwb @erights, any opinions on this?

**Comment by allenwb** [comment]
The original intent of `ArrayBuffer.isView` was to provide a way to determine if an object was a "view".  In other words if it had an [[ViewedArrayBuffer]] internal slot that could be accessed using the `buffer` method that is common to both Typed Arrays and `DataView` instances. `isView` was placed on ArrayBuffer instead of `DataView` or the anonymous %TypedArray% (and via inheritance ever typed array constructor) to avoid unnecessary redundancy.

The existence of SharedBuffer  really doesn't change the answer to the questions "is this object a view/can I access the buffer using the `buffer` method?" So, I don't see why we would want to have a redundant `SharedArrayBuffer.isView`.

If we (plausibly) need to provided a predicate for determining whether a buffer is sharable, I think a new method, perhaps `SharedArrayBuffer.isSharable(aBuffer)`, that  would be more appropriate.

**Comment by lars-t-hansen** [comment]
@allenwb, I like the way this is going :)

@binji @littledan @pizlonator -- any misgivings about just removing SharedArrayBuffer.isView, based on what Allen is writing?

**Comment by pizlonator** [comment]
No misgivings. :-)

-Filip

**Comment by binji** [comment]
sgtm!
