### ISSUE TITLE
Forward progress guarantees

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#5]
Shared memory and atomics rely on threads offering forward-progress guarantee in order to be useful. This spec therefore relies on improving workers along the lines of [Torvald Riegel's N4439 paper to the C++ standards committee](http://wg21.link/n4439).

**Comment by lars-t-hansen** [comment]
Agreed.  I will add prose to the "Web browser embedding" section at a minimum (and I've reached out to our standards people re the Worker spec issues), but to be embedding-neutral I probably also have to add something about agent semantics in general.

**Comment by lars-t-hansen** [comment]
In ES6 terms, this may be formalized in the context of jobs (ES6 8.4) having a forward-progress guarantee, which seems eminently possible, and workers being restated in terms of jobs, which is a bit more open but probably desirable.

**Comment by lars-t-hansen** [comment]
Bug filed against the WHATWG spec here: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29039.

**Comment by lars-t-hansen** [comment]
Current spec text proposes (lightweight) wording changes to ES6 to add a forward progress guarantee for jobs, with a reference to n4439 in a Note to bring it to the committee's attention, and also adds a suggestion in the non-normative section on agent mapping that workers should be restated in terms of jobs.

Once the spec goes to TC39 it will become natural to file the missing forward progress guarantee as a bug against ES262.

I will close this bug because I think the spec text now contains all the information herein.

**Comment by jfbastien** [comment]
Circling back, the following was added to C++17: http://wg21.link/p0296r2
