### ISSUE TITLE
Update LICENSE?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#53]
The current license is the MPL.  Presumably there's some Ecma and/or TC39 policy around this, and we should conform to it.

@bterlson, any guidance here?

**Comment by lars-t-hansen** [comment]
Looks like a free-for-all.

**Comment by bterlson** [comment]
Sorry I missed the original ping. License for the spec text can be anything you want for now, though you do give ECMA a copyright grant in order to incorporate the text into the final specification. Software should be licensed under BSD. Assuming you are using latest ecmarkup, if you add 'contributors' to the front-matter it will generate the legal boilerplate for you.

**Comment by lars-t-hansen** [comment]
Thanks.  I've added LICENSE files to the software subdirectories (test262/ and test-html/) where I note that the intended license is BSD; all prior commits in those directories had my name on them so that should be fine now.
