### ISSUE TITLE
Why not describe all agents that share a thread as a single agent?

### ISSUE THREAD

**Issue by erights** [tc39/ecmascript_sharedmem#66]
From https://axis-of-eval.org/shmem/agents-formatted.html

> An execution thread may be used as the execution thread by multiple agents only if none of the agents sharing the thread have a canBlock attribute that is true.
> 
> NOTE 1
> This is a case of bowing to reality, since browsers do share the main thread across tabs in the same process and will prohibit main-thread code from blocking. 

This assumes that if it is in a different tab, that we are constrained to describe it as a different agent, even if it shares a thread. If instead, we took all the computation that we currently describe as a set of agents sharing a thread and instead describe it as a single agent, what would be lost?

Sure they each have their named job queues. But these names are only a spec device anyway. The combined agent would merely have all these queues. All the agents that share a thread can only execute one job at a time from this overall job-queue set anyway?

I make this suggestion only to simplify the spec -- to remove unneeded distinctions. If there is some compensating spec complexity cost, then I withdraw the suggestion.

**Comment by lars-t-hansen** [comment]
> This assumes that if it is in a different tab, that we are constrained to describe it as a different agent, even if it shares a thread.

Yes.

> If instead, we took all the computation that we currently describe as a set of agents sharing a thread and instead describe it as a single agent, what would be lost?

I think I understand what you're getting at, but I don't yet understand how it simplifies anything.  We get rid of the caveat about the shared execution thread, to be sure.  And since we can have any number of job queues or queue sets and we can pick the queue to pick a job off any way we want we can interleave jobs running in multiple tabs even with just the one agent.  But we're trading the concept of execution thread (itself pretty lightweight) for an idea of a pool of queues.

Additionally, if it is just the one agent then it participates in multiple agent clusters that are otherwise unable to share memory (assuming agent clusters as a time-varying thing, though I know we're debating that).  I doubt that will be a deal breaker but it seems to add some complexity.

(I also suspect that long term we'll be happy to have independent agents that we can attach more information to, but that's neither here nor there.)

@domenic @allenwb: opinions?

**Comment by domenic** [comment]
I don't see what would be gained with this change. It would make the spec further away from the real world, and introduce a new level of abstraction (something that contains a job queue) that for some reason is not called "an agent". I agree it doesn't simplify anything as far as I can tell.

**Comment by erights** [comment]
If it doesn't help, I'm happy to withdraw the suggestion. I just hope we don't end up needing a new name for a new concept of "agents sharing a thread", as an intermediate level of aggregation between agent and agent cluster.

**Comment by lars-t-hansen** [comment]
> I just hope we don't end up needing a new name for a new concept of "agents sharing a thread", as an intermediate level of aggregation between agent and agent cluster.

I hope so too.  I'll close this issue but we'll remember the discussion if the problem comes up again once the two specs are more solid.
