### ISSUE TITLE
Atomicity: lock-free guarantees

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#7]
I opened the following issue on the WebAssembly repo, and I think it equally affects this repo:
https://github.com/WebAssembly/design/issues/300

I suggest we discuss JavaScript specifics here, and discuss high-level design issues over on the WebAssembly side.

**Comment by lars-t-hansen** [comment]
I commented in that bug.

From the JS perspective I think it's premature to start guaranteeing that any particular access size is lock-free.  (Indeed isLockFree, along with futexWakeOrRequeue, sticks out as a very un-JS optimization primitive in the current spec already and I would not be surprised if it runs into opposition.)

In particular, I see JS being used now (in node.js) in microcontroller systems, some of which are eg ARMv6-based.  ARMv6 (at least those with the Thumb-2 instruction set, though not the older ones) have 4-byte atomic ops but not 1-byte or 2-byte ops, I expect other microcontrollers are similar.  They may  not be multiprocessor systems but they are preemptively threaded and short of disabling interrupts the atomics must be properly implemented.  For weaker hardware there may not even be a 4-byte atomic operation.

For WebAssembly the situation might be different than for JS, I'm not sure, but for JS I'd prefer to not lock myself into the hardware than necessary, at least not yet.

**Comment by lars-t-hansen** [comment]
To follow up on that, I don't want to overstate the importance of the microcontroller space, but I note that the first Raspberry PI had an ARMv6 CPU that did not even support Thumb2 (an ARM1176JZ), though it was otherwise fairly beefy and can run Linux and js just fine.  If lying about the capabilities of the chip is precluded (and I think it should be :) then isLockFree(4) on a Model 1 Raspberry PI must arguably return false: The chip has native atomic exchange operations for 4 bytes and 1 byte (SWP, SWPB) but these would probably have to operate on a separate "lock" location to implement the proposed JS atomics.

**Comment by jfbastien** [comment]
As [discussed](https://github.com/WebAssembly/design/issues/300#issuecomment-132255381) in the wasm bug, having 4-byte atomics means 1- and 2-bytes are covered.

Agreed that lying about chip capabilities isn't an option.

On `SWP` and `SWPB`: I don't understand what you mean about operating on a separate lock location. They can be used as `cmpxchg`, albeit an undesirable one because it blocks all interrupts and hurts memory performance. On Linux systems I'd instead recommend using the [kernel user helpers](https://www.kernel.org/doc/Documentation/arm/kernel_user_helpers.txt), specifically `__kuser_cmpxchg` which is available if `__kuser_helper_version >= 2` (from kernel version 2.6.12). If the runtime doesn't know what's best then it can just punt to the kernel.

**Comment by lars-t-hansen** [comment]
@jfbastien, having 4-byte atomics means 1- and 2-bytes _could be_ covered.  It's a choice - and I think it's the right choice - but one could choose otherwise.  As I said (over in the WebAssembly thread), I've been told that the implementation advice for MIPS32 _is_ to choose otherwise, though I remain skeptical.

Regarding SWP: suppose you have one four-byte location (a pointer, say, in a lock-free data structure) and you want to implement CMPXCHG on that location, and all you have is SWP.  I'm not sure how I would do that without additional storage.  SWP is effectively just an exchange operation, it has no compare built into it.

**Comment by lars-t-hansen** [comment]
Issue #10 discusses whether RMW on a larger word is even a valid implementation technique (in the context of the present spec) for atomics on platforms that don't have byte and halfword atomic accesses.

**Comment by jfbastien** [comment]
Ah you're right, `SWP` behaves like `xchg`.

**Comment by lars-t-hansen** [comment]
@sunfishcode notes in the referenced wasm bug that "FWIW, I looked up the original Raspberry Pi and it has an ARM1176JZF-S which according to ARM does have ldrexh, strexh, ldrexb, and strexb."

So the situation on the RPi1 is a moot point - just for the record.

**Comment by lars-t-hansen** [comment]
Conclusion (for now): the spec will not make any guarantees about any particular size being lock-free.

**Comment by jfbastien** [comment]
From C++ `atomic_flag` with methods `test_and_set` and `clear` says:

> Operations on an object of type `atomic_flag` shall be lock-free. [ _Note:_ Hence the operations should also be address-free. No other type requires lock-free operations, so the `atomic_flag` type is the minimum hardware-implemented type needed to conform to this International standard. The remaining types can be emulated with `atomic_flag`, though with less than ideal properties. — _end note_ ]

It may be worth having a similar parallel in SAB. We could require that SAB's `atomic_flag` be given a 4-byte location and the underlying `test_and_set` and `clear` will only touch the bits that the hardware can guarantee as lock-free.
