### ISSUE TITLE
Convert value to be stored by ToInteger rather than ToNumber?  (was: What equality does compareExchange use?)

### ISSUE THREAD

**Issue by erights** [tc39/ecmascript_sharedmem#72]
At http://tc39.github.io/ecmascript_sharedmem/shmem.html#Atomics.compareExchange step 16.b:

> If r is the same number value as x

I'm curious about the choice of language. Is the purpose of this to allow -0 and 0 to be judged equal in this operation? If these were integers, obviously that would not be a problem. But this section seems to purposely allow floating point. Other hazards of stating things this way is that NaN and the Infinity's have no number value.

I would guess that the actual instructions we have in mind don't take such niceties into account but compare bit values. If that's true, then this is definitely the wrong language.

**Comment by lars-t-hansen** [comment]
ValidateSharedIntegerTypedArray explicitly rules out floating point.

There is very little demand for atomic operations on floating point and some active resistance to it.  One of the reasons - but by no means the only one - is that equality for compareExchange has to be bitwise to be meaningful at the hardware level.  +0 vs -0 is one issue; different NaN representations is probably a worse one.

**Comment by erights** [comment]
Yes, I did miss that ValidateSharedIntegerTypedArray rules out floating point, thanks. However, in that case, I think the language "same number value" is confusing, as is the use of a ToNumber conversion rather than ToInteger. How about "same" and ToInteger?

**Comment by lars-t-hansen** [comment]
(Reopening and relabeling.)

It should now be possible to make a change to `ToInteger`.  I'm not completely sure that's a desirable change, but it's possible.  Two remarks about that:
- One reason `ToNumber` is being used in these algorithms is that [`IntegerIndexedElementSet`](https://tc39.github.io/ecma262/#sec-integerindexedelementset) uses ToNumber; the ultimate conversion is defered to `SetValueInBuffer`.  The atomic ops were modeled on the former operation.  Of course `IntegerIndexedElementSet` must handle floating point.
- Previously, the atomic ops could operate also on `Uint8ClampedArray`, where the change would be visible: `ToInteger(3.75)` = 3 but `ToUint8Clamped(3.75)` = 4, and deferring the final conversion to `IntegerIndexedElementSet` would be the best thing.  But the atomics no longer work on `Uint8ClampedArray`, so that's a moot point too.

The only reason I'm hesitant to make the change is because of the affinity with `IntegerIndexedElementSet`, but that's not a very good reason.  Thoughts about that?

**Comment by jfbastien** [comment]
For reference, C++ defines `cmpxchg` in terms of `memcpy` and `memcmp` because that's what hardware actually does. It avoids the problems with floating-point.

**Comment by lars-t-hansen** [comment]
With Issue #78 the connection with IntegerIndexedElementSet is ever more tenuous, so I'll make this change.  Thanks.

**Comment by jfbastien** [comment]
Could you clarify which change you're making? Floating-point cmpxchg should compare bits.

**Comment by lars-t-hansen** [comment]
cc @binji : spec change, though probably invisible to the implementation.

@jfbastien, we have no floating-point atomics, I'm just changing the conversion op for Atomics.{store,add,and,or,xor,sub} from ToNumber to ToInteger.

**Comment by jfbastien** [comment]
OK ty, I think my comment raced with your update, so I wasn't sure what you were going to change :-)
