### ISSUE TITLE
Is the agent spec a subspec, or standalone, or an adjustment?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#83]
@domenic, @erights, I need some input here:

Which of these best characterizes the agents spec:
- it's a subproposal of the SAB spec and should be tied closely to it
- it's a proposal all of its own and needs to go through the TC39 process as such
- it's an adjustment to the current spec and can just be presented as a PR

(I'd probably prefer for it to be the latter but I suspect it may be one of the former, which is why I'm asking.)

**Comment by domenic** [comment]
I think it's borderline, and you might need to present it to the committee. I agree adjustment to the current spec would be nice.

To start that discussion, you'd need to be very clear (e.g. in bullet point form on slides) about what new normative requirements on ES implementations and on host environments this introduces.

**Comment by littledan** [comment]
I like the separation of agents into a separate document. I think it should be OK to _not_ block SharedArrayBuffer on agents being fully specified on agents being fully specified. Agents seem like part of the glue that connects ECMAScript with host environments--and a lot of that glue has not been so formally specified until recently, and remains incomplete. It is a good thing to specify, and I think we should work on it, but it's OK to separate out.

I also think that, as glue, it makes sense to pursue agents in a pull request, rather than something that goes through the stage process. Agents don't have any external API. Agents appear to be controversial, though, so it makes sense to require consensus before going into the spec. But all that will evolve with respect to them is spec language itself; there won't be any new implementations or test262 tests.

For now, cross-referencing the shared-memory spec to the agents spec seems good. These cross references could probably use a little bit of cleaning up in the shared memory spec. The current draft spec has a number of skeletal headings which just have the cross-references--probably better to include those links at the usage site directly instead. If SharedArrayBuffer goes in before Agents (which I argue should be possible), the language could be changed to simply be a bit more vague about these concepts.

**Comment by littledan** [comment]
Background question: Is the motivation for all of this to be able to specify the forward progress guarantee? Was that required by the committee? Or is there something else motivating this, like the general desire to be more precise about our HTML integration?

**Comment by lars-t-hansen** [comment]
The agents work fell out of the shmem work because I needed to talk about (1) forward progress and (2) observable effects in shared memory, not just memory values changing (racily) but more importantly futexWait/futexWake: the abstract algorithms for those functions must have an idea of "agent" as a semantic object.

It is arguably the case that forward progress needs to be a concept independently of the shared memory work, since a number of things around workers don't make much sense without a forward progress guarantee (but then I think that's true for a number of things around workers).

The more I look at it the more the current agents spec has two cleanly separated parts: One part cleans up the current spec and packages the existing execution machinery with the agent properties and an execution thread and forward progress into one bundle called "agent".  (The one existing property from the spec that fits in this scheme is the value for isLittleEndian, which appears out of thin air in GetValueFromBuffer and SetValueInBuffer.)  The other part is concerned with shared memory: agent clusters, their suspend-together semantics, and their termination properties.

I would argue that there are interesting discussions to be had about the suspend-together and termination behaviors even without shared memory, consider what happens if a shared worker waits for a message from a page that has been suspended or removed by the user agent.  But the need is much more acute for shared memory since it has blocking primitives.

The "clean things up" part of the agent spec is an obvious PR candidate.  This includes the notion of execution thread, forward progress, and _maybe_ the [[CanBlock]] property since that interacts with execution thread and forward progress.

The other part of the agent spec could be moved back into the shmem spec, since the agent spec (reduced to a PR eliciting scant controversy) will have the necessary hooks.

**Comment by lars-t-hansen** [comment]
I think this has been resolved, as follows:
- There is a fairly simple PR against ES262, https://github.com/tc39/ecma262/pull/522, that defines agents and a few things around agents such as the currently running agent and a lightweight notion of forward progress.  It really only surfaces what's already in ES262 by naming a few things that were previously unnamed.  This PR is currently clean but has been stalled, probably because it was inactive for quite a while.
- The shared memory spec then builds on that PR to define agent clusters, talk about termination, and so on.
